### PR TITLE
Support for const annotations

### PR DESCRIPTION
**Pull request by miniBill**

### CODE REVIEW

**Comment by wolfadex** [comment]
@miniBill do you have an example of what this covers?

**Comment by miniBill** [comment]
JSON Schema definition: https://json-schema.org/understanding-json-schema/reference/const

Basically what I'm using it as is that I have an API that always returns 200 and has a _beautiful_ `success : Bool` field, and I want to use `const : true` and `const : false` inside a `oneOf` to codegen two variants instead of having to check the boolean in all callsites.

There will be another PR fixing the `oneOf` with records in responses, cause it seems we don't do that yet

**Comment by miniBill** [comment]
This is "blocked" by #155 to get a clearer diff

**Comment by wolfadex** [comment]
Awesome! Don't forget to add things to the changelog, if you remember. If not I'll go through it all anyways before a release

**Pull request merged**
